"""
Visualization Module (Facade Layer)
Maintains 100% backward compatibility for existing imports across the project.
All concrete chart implementations are modularized into `charts/macro_charts.py`
and `charts/stock_charts.py`.
"""
from charts.theme import filter_by_timeframe, apply_chart_theme
from charts.macro_charts import (
    create_treasury_chart,
    create_unemployment_chart,
    create_credit_spread_chart,
    create_fed_balance_sheet_chart,
    create_gold_oil_ratio_chart,
    create_real_yield_breakeven_chart,
    create_nfci_chart,
    create_net_liquidity_chart,
    create_sofr_iorb_chart,
    create_top10_concentration_chart,
    create_vix_chart,
    create_cnn_fear_greed_chart,
    create_yield_spreads_chart,
    create_jobless_claims_chart,
    create_dxy_chart,
    create_inflation_wages_chart,
    create_sahm_rule_chart,
    create_core_capex_chart,
    create_m2_money_supply_chart,
    create_sloos_credit_chart,
    create_erp_chart,
    create_skew_dix_chart,
    create_cross_asset_ratios_chart,
    create_move_chart,
    create_term_premium_chart,
    create_epu_chart,
    create_commercial_loans_chart,
    create_personal_saving_rate_chart,
    create_cicc_quadrant_chart,
)
from charts.stock_charts import (
    create_stock_price_chart,
    create_relative_performance_chart,
    create_financial_trends_chart,
    create_pe_ps_band_chart,
    create_technical_momentum_chart,
    create_max_pain_chart,
    create_volatility_momentum_chart,
)

__all__ = [
    "filter_by_timeframe",
    "apply_chart_theme",
    "create_treasury_chart",
    "create_unemployment_chart",
    "create_credit_spread_chart",
    "create_fed_balance_sheet_chart",
    "create_gold_oil_ratio_chart",
    "create_real_yield_breakeven_chart",
    "create_nfci_chart",
    "create_net_liquidity_chart",
    "create_sofr_iorb_chart",
    "create_top10_concentration_chart",
    "create_vix_chart",
    "create_cnn_fear_greed_chart",
    "create_yield_spreads_chart",
    "create_jobless_claims_chart",
    "create_dxy_chart",
    "create_inflation_wages_chart",
    "create_sahm_rule_chart",
    "create_core_capex_chart",
    "create_m2_money_supply_chart",
    "create_sloos_credit_chart",
    "create_erp_chart",
    "create_skew_dix_chart",
    "create_cross_asset_ratios_chart",
    "create_move_chart",
    "create_term_premium_chart",
    "create_epu_chart",
    "create_commercial_loans_chart",
    "create_personal_saving_rate_chart",
    "create_cicc_quadrant_chart",
    "create_stock_price_chart",
    "create_relative_performance_chart",
    "create_financial_trends_chart",
    "create_pe_ps_band_chart",
    "create_technical_momentum_chart",
    "create_max_pain_chart",
    "create_volatility_momentum_chart",
]

