name: Daily Data Update and Commit

on:
  schedule:
    # Runs at 10:00 UTC every day. Adjust as needed.
    # '0 10 * * *' (e.g., Beijing Time 6 PM, or US Eastern Time 6 AM in daylight saving)
    - cron: '0 10 * * *' 
  workflow_dispatch:
    # Allows manual triggering of the workflow from the GitHub Actions tab

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Crucial: fetches the full history for comparison and push
          fetch-depth: 0 
          # Uses the default token with read/write permissions
          token: ${{ secrets.GITHUB_TOKEN }} 

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Recommended stable version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Need pandas and requests for the data script
          pip install pandas requests

      - name: Run data update script and check for changes
        id: run_script
        run: |
          python update_data.py

      - name: Check if commit is needed and Push changes
        # This step uses the special output from the python script to commit only if an update occurred
        if: success() && steps.run_script.outputs.commit_needed == 'true'
        run: |
          # Configure Git identity for the automated bot
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add the updated file
          git add daily-treasury-rates.csv
          
          # Commit the changes
          git commit -m "Auto: Update daily-treasury-rates.csv to ${{ env.LATEST_DATE }}"
          
          # Push the changes to the master branch
          git push
